name: restaurant_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animations: ^2.0.4
  bloc: ^8.1.0
  blurrycontainer: ^1.0.2
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.7.1
  custom_text: ^0.5.1
  dio: ^4.0.6
  equatable: ^2.0.5
  extended_nested_scroll_view: ^5.1.3
  #firebase_auth: ^3.9.0
  #firebase_core: ^1.22.0
  flavor:
    path: flavor
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  #flutter_facebook_auth: ^4.4.1
  flutter_native_splash: ^2.2.7
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.4
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.12
  #google_sign_in: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  linked_scroll_controller: ^0.2.0
  otp_text_field: ^1.1.3
  progress_indicators: ^1.0.0
  qr_code_scanner: ^1.0.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  syncfusion_flutter_gauges: ^20.2.44
  vertical_tab_bar_view: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - flavor/
    - flavor/assets/
    - flavor/assets/images/

flutter_native_splash:
  #color: "#42a5f5"
  background_image: "assets/images/splash.png"
  fullscreen: true
